baseURL: "https://umektumacademy.com"
title: "Braille Quran"
theme: "ananke"
enableGitInfo: true

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

enableRobotsTXT: true

languages:
  en:
    label: English
    weight: 1
    title: "Braille Quran"
    contentDir: content/en
    params:
      description: "Braille Quran – Accessible Quran Resources"
  tr:
    label: Türkçe
    weight: 2
    title: "Braille Kur'an – Görme Engelliler İçin Kur'an Kaynakları"
    contentDir: content/tr
    params:
      description: "Braille Quran – Erişilebilir Kur'an Kaynakları"
  de:
    label: Deutsch
    weight: 3
    title: "Braille Quran"
    contentDir: content/de
    params:
      description: "Braille Quran – Barrierefreie Koran-Ressourcen"
  fr:
    label: Français
    weight: 4
    title: "Braille Quran"
    contentDir: content/fr
    params:

      description: "Braille Quran – Ressources Coraniques Accessibles"

params:
  background_color_class: "bg-dark-blue"
  ananke:
    show_recent_posts: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: false
