baseURL: "https://braillequran.org/"
title: "BrailleQuran"
theme: "ananke"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

enableRobotsTXT: true

languages:
  en:
    languageName: English
    weight: 1
    title: "BrailleQuran"
    contentDir: content/en
    params:
      description: "BrailleQuran – Accessible Quran Resources"
    menus:
      main:
        - name: Home
          pageRef: /
          weight: 1
  tr:
    languageName: Türkçe
    weight: 2
    title: "BrailleQuran"
    contentDir: content/tr
    params:
      description: "BrailleQuran – Erişilebilir Kur'an Kaynakları"
    menus:
      main:
        - name: Ana Sayfa
          pageRef: /
          weight: 1
        - name: Arapça Braille Okuma Notlar 
          pageRef: /general_reading_notes
          weight: 5
        - name: Braille Noktalar
          pageRef: /braille_dots
          weight: 4
        - name: Tüm Braille Semboller
          pageRef: /all_symbols
          weight: 7
        - name: Kuveyt Sistemi
          pageRef: /kuwaiti_system
          weight: 8
  de:
    languageName: Deutsch
    weight: 3
    title: "BrailleQuran"
    contentDir: content/de
    params:
      description: "BrailleQuran – Barrierefreie Koran-Ressourcen"
    menus:
      main:
        - name: Startseite
          pageRef: /
          weight: 1
  fr:
    languageName: Français
    weight: 4
    title: "BrailleQuran"
    contentDir: content/fr
    params:
      description: "BrailleQuran – Ressources Coraniques Accessibles"
    menus:
      main:
        - name: Accueil
          pageRef: /
          weight: 1

params:
  background_color_class: "bg-dark-blue"
  ananke:
    show_recent_posts: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: false
